### ISSUE TITLE
Resolution Issue

### ISSUE THREAD

**Issue by ARCX95** [Hegemege/molek-syntez-solitaire-bot#2]
Currently my screen resolution is 1440x900, playing the game on fullscreen and pixel scaling is set to Full, i adjusted the GAME_WIDTH and GAME_HEIGHT to my res, had to adjust NEW_GAME_BUTTON as well and after this the game just clicks on new game and then does nothing, actually it shows the same error as the previous issue opened here on Github, https://i.imgur.com/N8zPizd.png, i'm not sure if i adjusted it correctly or do i need to do something else?, the instructions only say that you may need to tweak the coords but nothing really specific so i'm a bit lost.

**Comment by Hegemege** [comment]
Right, I never really tested the script in resolutions lower than 1080p. The game view is centered a bit differently in lower res, and might even have some scaling going on. 

You can compare to the reference image in the repo - if the cards have the same pixel size, then you could get it working just tweaking those variables to get the cropped game area to match what is cropped from 1080p and above.

I might take a look later at supporting lower resolutions. If you want to try it yourself, I'd begin by halting the script after it takes a screenshot and dump it on the disk to see what sort of data the game outputs at 900p and go from there.

**Comment by ARCX95** [comment]
Heh this is what i got by comparing them: https://i.imgur.com/I3Ji7Ui.jpg, currently i can't use 1080p res right now so i guess i won't be able to use the bot, that's fine though i already got the Moralist achievement and getting the 10 wins is easy, i'll just skip the 100 one. Thanks for the help.

**Comment by MakoSipper** [comment]
It worked for me with the correct game button values for 1080p fullscreen @ line 29:
`NEW_GAME_BUTTON = (960, 1035)`

Also, I have dual monitors, so I had to change line 259 to:
`width = image.size[0]/2`

**Comment by Hegemege** [comment]
There was a breaking change in the screenshot grabbing library used by the script. I updated to use the one that comes with PIL instead (module ImageGrab). I guess if you run the game on a secondary monitor, the screengrab will be on the wrong monitor. Would need to use a library that grabs the screen coordinates of only the game window (both windowed and fullscreen + borderless) and then use that offset for the screengrab.
