### ISSUE TITLE
It doesn't really work

### ISSUE THREAD

**Issue by Bircck** [Hegemege/molek-syntez-solitaire-bot#3]
I've tried a bunch of different configurations and made sure It's not something on my end and i continously get the same error. 

line 214, in replay_actions
    from_position = CLICK_STACKS[action[0][0]][action[0][1]]
TypeError: 'int' object is not subscriptable

I don't know what's causing the error, also It isn't able to hit the new game button with the coordinates , (1280, 1215) like the original code but someone suggested (1000, 1050) on 1080p monitors and that works fine.

**Comment by Hegemege** [comment]
Looks like something had changed in one of the dependencies, pyscreenshot, which caused this issue to occur. In essence, the script took a screenshot of the wrong area and could not parse the cards from that. Please check the readme again, I changed the instructions for installing the dependencies so make sure to update them before trying again

**Comment by Bircck** [comment]
Thanks so so much for looking into it and fixing it, It works like a charm now. The only thing I would suggest is to possibly add to the read.me to change the new game button coordinates to (1000, 1050) _(if you're 1080p)_ but other than that, happy new year and again thanks ^^
